// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/content/v1/content.proto

package contentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChapterContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelSlug     string                 `protobuf:"bytes,1,opt,name=novel_slug,json=novelSlug,proto3" json:"novel_slug,omitempty"`
	ChapterNumber int32                  `protobuf:"varint,2,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterContentRequest) Reset() {
	*x = GetChapterContentRequest{}
	mi := &file_proto_content_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterContentRequest) ProtoMessage() {}

func (x *GetChapterContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterContentRequest.ProtoReflect.Descriptor instead.
func (*GetChapterContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *GetChapterContentRequest) GetNovelSlug() string {
	if x != nil {
		return x.NovelSlug
	}
	return ""
}

func (x *GetChapterContentRequest) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

type ChapterContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NovelId       string                 `protobuf:"bytes,2,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	NovelTitle    string                 `protobuf:"bytes,3,opt,name=novel_title,json=novelTitle,proto3" json:"novel_title,omitempty"`
	NovelSlug     string                 `protobuf:"bytes,4,opt,name=novel_slug,json=novelSlug,proto3" json:"novel_slug,omitempty"`
	Number        int32                  `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	WordCount     int32                  `protobuf:"varint,8,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	TotalChapters int32                  `protobuf:"varint,9,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterContent) Reset() {
	*x = ChapterContent{}
	mi := &file_proto_content_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterContent) ProtoMessage() {}

func (x *ChapterContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterContent.ProtoReflect.Descriptor instead.
func (*ChapterContent) Descriptor() ([]byte, []int) {
	return file_proto_content_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *ChapterContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChapterContent) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *ChapterContent) GetNovelTitle() string {
	if x != nil {
		return x.NovelTitle
	}
	return ""
}

func (x *ChapterContent) GetNovelSlug() string {
	if x != nil {
		return x.NovelSlug
	}
	return ""
}

func (x *ChapterContent) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ChapterContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChapterContent) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ChapterContent) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *ChapterContent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAdjacentChaptersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NovelId        string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,2,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAdjacentChaptersRequest) Reset() {
	*x = GetAdjacentChaptersRequest{}
	mi := &file_proto_content_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdjacentChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdjacentChaptersRequest) ProtoMessage() {}

func (x *GetAdjacentChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdjacentChaptersRequest.ProtoReflect.Descriptor instead.
func (*GetAdjacentChaptersRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdjacentChaptersRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *GetAdjacentChaptersRequest) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

type AdjacentChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPrev       bool                   `protobuf:"varint,1,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	HasNext       bool                   `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	PrevNumber    int32                  `protobuf:"varint,3,opt,name=prev_number,json=prevNumber,proto3" json:"prev_number,omitempty"`
	NextNumber    int32                  `protobuf:"varint,4,opt,name=next_number,json=nextNumber,proto3" json:"next_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjacentChaptersResponse) Reset() {
	*x = AdjacentChaptersResponse{}
	mi := &file_proto_content_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjacentChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjacentChaptersResponse) ProtoMessage() {}

func (x *AdjacentChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjacentChaptersResponse.ProtoReflect.Descriptor instead.
func (*AdjacentChaptersResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *AdjacentChaptersResponse) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

func (x *AdjacentChaptersResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *AdjacentChaptersResponse) GetPrevNumber() int32 {
	if x != nil {
		return x.PrevNumber
	}
	return 0
}

func (x *AdjacentChaptersResponse) GetNextNumber() int32 {
	if x != nil {
		return x.NextNumber
	}
	return 0
}

var File_proto_content_v1_content_proto protoreflect.FileDescriptor

const file_proto_content_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/content/v1/content.proto\x12\n" +
	"content.v1\"`\n" +
	"\x18GetChapterContentRequest\x12\x1d\n" +
	"\n" +
	"novel_slug\x18\x01 \x01(\tR\tnovelSlug\x12%\n" +
	"\x0echapter_number\x18\x02 \x01(\x05R\rchapterNumber\"\xa8\x02\n" +
	"\x0eChapterContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnovel_id\x18\x02 \x01(\tR\anovelId\x12\x1f\n" +
	"\vnovel_title\x18\x03 \x01(\tR\n" +
	"novelTitle\x12\x1d\n" +
	"\n" +
	"novel_slug\x18\x04 \x01(\tR\tnovelSlug\x12\x16\n" +
	"\x06number\x18\x05 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"word_count\x18\b \x01(\x05R\twordCount\x12%\n" +
	"\x0etotal_chapters\x18\t \x01(\x05R\rtotalChapters\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"`\n" +
	"\x1aGetAdjacentChaptersRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\x12'\n" +
	"\x0fcurrent_chapter\x18\x02 \x01(\x05R\x0ecurrentChapter\"\x92\x01\n" +
	"\x18AdjacentChaptersResponse\x12\x19\n" +
	"\bhas_prev\x18\x01 \x01(\bR\ahasPrev\x12\x19\n" +
	"\bhas_next\x18\x02 \x01(\bR\ahasNext\x12\x1f\n" +
	"\vprev_number\x18\x03 \x01(\x05R\n" +
	"prevNumber\x12\x1f\n" +
	"\vnext_number\x18\x04 \x01(\x05R\n" +
	"nextNumber2\xcc\x01\n" +
	"\x0eContentService\x12U\n" +
	"\x11GetChapterContent\x12$.content.v1.GetChapterContentRequest\x1a\x1a.content.v1.ChapterContent\x12c\n" +
	"\x13GetAdjacentChapters\x12&.content.v1.GetAdjacentChaptersRequest\x1a$.content.v1.AdjacentChaptersResponseB1Z/github.com/novelhive/proto/content/v1;contentv1b\x06proto3"

var (
	file_proto_content_v1_content_proto_rawDescOnce sync.Once
	file_proto_content_v1_content_proto_rawDescData []byte
)

func file_proto_content_v1_content_proto_rawDescGZIP() []byte {
	file_proto_content_v1_content_proto_rawDescOnce.Do(func() {
		file_proto_content_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_v1_content_proto_rawDesc), len(file_proto_content_v1_content_proto_rawDesc)))
	})
	return file_proto_content_v1_content_proto_rawDescData
}

var file_proto_content_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_content_v1_content_proto_goTypes = []any{
	(*GetChapterContentRequest)(nil),   // 0: content.v1.GetChapterContentRequest
	(*ChapterContent)(nil),             // 1: content.v1.ChapterContent
	(*GetAdjacentChaptersRequest)(nil), // 2: content.v1.GetAdjacentChaptersRequest
	(*AdjacentChaptersResponse)(nil),   // 3: content.v1.AdjacentChaptersResponse
}
var file_proto_content_v1_content_proto_depIdxs = []int32{
	0, // 0: content.v1.ContentService.GetChapterContent:input_type -> content.v1.GetChapterContentRequest
	2, // 1: content.v1.ContentService.GetAdjacentChapters:input_type -> content.v1.GetAdjacentChaptersRequest
	1, // 2: content.v1.ContentService.GetChapterContent:output_type -> content.v1.ChapterContent
	3, // 3: content.v1.ContentService.GetAdjacentChapters:output_type -> content.v1.AdjacentChaptersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_content_v1_content_proto_init() }
func file_proto_content_v1_content_proto_init() {
	if File_proto_content_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_v1_content_proto_rawDesc), len(file_proto_content_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_content_v1_content_proto_goTypes,
		DependencyIndexes: file_proto_content_v1_content_proto_depIdxs,
		MessageInfos:      file_proto_content_v1_content_proto_msgTypes,
	}.Build()
	File_proto_content_v1_content_proto = out.File
	file_proto_content_v1_content_proto_goTypes = nil
	file_proto_content_v1_content_proto_depIdxs = nil
}
