// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *SearchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TookMs        float32                `protobuf:"fixed32,4,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetTookMs() float32 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Synopsis      string                 `protobuf:"bytes,4,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Genres        []string               `protobuf:"bytes,7,rep,name=genres,proto3" json:"genres,omitempty"`
	Score         float32                `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	Highlight     string                 `protobuf:"bytes,9,opt,name=highlight,proto3" json:"highlight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_proto_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SearchHit) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *SearchHit) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SearchHit) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *SearchHit) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *SearchHit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetHighlight() string {
	if x != nil {
		return x.Highlight
	}
	return ""
}

type AutocompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteRequest) Reset() {
	*x = AutocompleteRequest{}
	mi := &file_proto_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteRequest) ProtoMessage() {}

func (x *AutocompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteRequest.ProtoReflect.Descriptor instead.
func (*AutocompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *AutocompleteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AutocompleteRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AutocompleteResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Suggestions   []*AutocompleteSuggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteResponse) Reset() {
	*x = AutocompleteResponse{}
	mi := &file_proto_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteResponse) ProtoMessage() {}

func (x *AutocompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteResponse.ProtoReflect.Descriptor instead.
func (*AutocompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *AutocompleteResponse) GetSuggestions() []*AutocompleteSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type AutocompleteSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteSuggestion) Reset() {
	*x = AutocompleteSuggestion{}
	mi := &file_proto_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteSuggestion) ProtoMessage() {}

func (x *AutocompleteSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteSuggestion.ProtoReflect.Descriptor instead.
func (*AutocompleteSuggestion) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *AutocompleteSuggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AutocompleteSuggestion) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AutocompleteSuggestion) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type IndexNovelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Synopsis      string                 `protobuf:"bytes,4,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Genres        []string               `protobuf:"bytes,7,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,9,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexNovelRequest) Reset() {
	*x = IndexNovelRequest{}
	mi := &file_proto_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexNovelRequest) ProtoMessage() {}

func (x *IndexNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexNovelRequest.ProtoReflect.Descriptor instead.
func (*IndexNovelRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *IndexNovelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IndexNovelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IndexNovelRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *IndexNovelRequest) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *IndexNovelRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *IndexNovelRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *IndexNovelRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *IndexNovelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IndexNovelRequest) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

type RemoveNovelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNovelRequest) Reset() {
	*x = RemoveNovelRequest{}
	mi := &file_proto_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNovelRequest) ProtoMessage() {}

func (x *RemoveNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNovelRequest.ProtoReflect.Descriptor instead.
func (*RemoveNovelRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveNovelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_proto_search_v1_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_v1_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_v1_search_proto_rawDescGZIP(), []int{8}
}

func (x *IndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_search_v1_search_proto protoreflect.FileDescriptor

const file_proto_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/search/v1/search.proto\x12\tsearch.v1\"\x84\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"}\n" +
	"\x0eSearchResponse\x12(\n" +
	"\x04hits\x18\x01 \x03(\v2\x14.search.v1.SearchHitR\x04hits\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x17\n" +
	"\atook_ms\x18\x04 \x01(\x02R\x06tookMs\"\xe2\x01\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1a\n" +
	"\bsynopsis\x18\x04 \x01(\tR\bsynopsis\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06genres\x18\a \x03(\tR\x06genres\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x1c\n" +
	"\thighlight\x18\t \x01(\tR\thighlight\"A\n" +
	"\x13AutocompleteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"[\n" +
	"\x14AutocompleteResponse\x12C\n" +
	"\vsuggestions\x18\x01 \x03(\v2!.search.v1.AutocompleteSuggestionR\vsuggestions\"Z\n" +
	"\x16AutocompleteSuggestion\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\"\xf5\x01\n" +
	"\x11IndexNovelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1a\n" +
	"\bsynopsis\x18\x04 \x01(\tR\bsynopsis\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06genres\x18\a \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\t \x01(\x05R\rtotalChapters\"$\n" +
	"\x12RemoveNovelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\rIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb3\x02\n" +
	"\rSearchService\x12C\n" +
	"\fSearchNovels\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponse\x12O\n" +
	"\fAutocomplete\x12\x1e.search.v1.AutocompleteRequest\x1a\x1f.search.v1.AutocompleteResponse\x12D\n" +
	"\n" +
	"IndexNovel\x12\x1c.search.v1.IndexNovelRequest\x1a\x18.search.v1.IndexResponse\x12F\n" +
	"\vRemoveNovel\x12\x1d.search.v1.RemoveNovelRequest\x1a\x18.search.v1.IndexResponseB/Z-github.com/novelhive/proto/search/v1;searchv1b\x06proto3"

var (
	file_proto_search_v1_search_proto_rawDescOnce sync.Once
	file_proto_search_v1_search_proto_rawDescData []byte
)

func file_proto_search_v1_search_proto_rawDescGZIP() []byte {
	file_proto_search_v1_search_proto_rawDescOnce.Do(func() {
		file_proto_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_v1_search_proto_rawDesc), len(file_proto_search_v1_search_proto_rawDesc)))
	})
	return file_proto_search_v1_search_proto_rawDescData
}

var file_proto_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),          // 0: search.v1.SearchRequest
	(*SearchResponse)(nil),         // 1: search.v1.SearchResponse
	(*SearchHit)(nil),              // 2: search.v1.SearchHit
	(*AutocompleteRequest)(nil),    // 3: search.v1.AutocompleteRequest
	(*AutocompleteResponse)(nil),   // 4: search.v1.AutocompleteResponse
	(*AutocompleteSuggestion)(nil), // 5: search.v1.AutocompleteSuggestion
	(*IndexNovelRequest)(nil),      // 6: search.v1.IndexNovelRequest
	(*RemoveNovelRequest)(nil),     // 7: search.v1.RemoveNovelRequest
	(*IndexResponse)(nil),          // 8: search.v1.IndexResponse
}
var file_proto_search_v1_search_proto_depIdxs = []int32{
	2, // 0: search.v1.SearchResponse.hits:type_name -> search.v1.SearchHit
	5, // 1: search.v1.AutocompleteResponse.suggestions:type_name -> search.v1.AutocompleteSuggestion
	0, // 2: search.v1.SearchService.SearchNovels:input_type -> search.v1.SearchRequest
	3, // 3: search.v1.SearchService.Autocomplete:input_type -> search.v1.AutocompleteRequest
	6, // 4: search.v1.SearchService.IndexNovel:input_type -> search.v1.IndexNovelRequest
	7, // 5: search.v1.SearchService.RemoveNovel:input_type -> search.v1.RemoveNovelRequest
	1, // 6: search.v1.SearchService.SearchNovels:output_type -> search.v1.SearchResponse
	4, // 7: search.v1.SearchService.Autocomplete:output_type -> search.v1.AutocompleteResponse
	8, // 8: search.v1.SearchService.IndexNovel:output_type -> search.v1.IndexResponse
	8, // 9: search.v1.SearchService.RemoveNovel:output_type -> search.v1.IndexResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_search_v1_search_proto_init() }
func file_proto_search_v1_search_proto_init() {
	if File_proto_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_v1_search_proto_rawDesc), len(file_proto_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_v1_search_proto_goTypes,
		DependencyIndexes: file_proto_search_v1_search_proto_depIdxs,
		MessageInfos:      file_proto_search_v1_search_proto_msgTypes,
	}.Build()
	File_proto_search_v1_search_proto = out.File
	file_proto_search_v1_search_proto_goTypes = nil
	file_proto_search_v1_search_proto_depIdxs = nil
}
