// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: novel.proto

package novelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NovelService_GetNovel_FullMethodName      = "/novel.v1.NovelService/GetNovel"
	NovelService_ListNovels_FullMethodName    = "/novel.v1.NovelService/ListNovels"
	NovelService_CreateNovel_FullMethodName   = "/novel.v1.NovelService/CreateNovel"
	NovelService_UpdateNovel_FullMethodName   = "/novel.v1.NovelService/UpdateNovel"
	NovelService_DeleteNovel_FullMethodName   = "/novel.v1.NovelService/DeleteNovel"
	NovelService_GetChapter_FullMethodName    = "/novel.v1.NovelService/GetChapter"
	NovelService_ListChapters_FullMethodName  = "/novel.v1.NovelService/ListChapters"
	NovelService_CreateChapter_FullMethodName = "/novel.v1.NovelService/CreateChapter"
	NovelService_UpdateChapter_FullMethodName = "/novel.v1.NovelService/UpdateChapter"
	NovelService_DeleteChapter_FullMethodName = "/novel.v1.NovelService/DeleteChapter"
	NovelService_ListGenres_FullMethodName    = "/novel.v1.NovelService/ListGenres"
	NovelService_CreateGenre_FullMethodName   = "/novel.v1.NovelService/CreateGenre"
	NovelService_DeleteGenre_FullMethodName   = "/novel.v1.NovelService/DeleteGenre"
)

// NovelServiceClient is the client API for NovelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NovelServiceClient interface {
	GetNovel(ctx context.Context, in *GetNovelRequest, opts ...grpc.CallOption) (*Novel, error)
	ListNovels(ctx context.Context, in *ListNovelsRequest, opts ...grpc.CallOption) (*ListNovelsResponse, error)
	CreateNovel(ctx context.Context, in *CreateNovelRequest, opts ...grpc.CallOption) (*Novel, error)
	UpdateNovel(ctx context.Context, in *UpdateNovelRequest, opts ...grpc.CallOption) (*Novel, error)
	DeleteNovel(ctx context.Context, in *DeleteNovelRequest, opts ...grpc.CallOption) (*DeleteNovelResponse, error)
	GetChapter(ctx context.Context, in *GetChapterRequest, opts ...grpc.CallOption) (*Chapter, error)
	ListChapters(ctx context.Context, in *ListChaptersRequest, opts ...grpc.CallOption) (*ListChaptersResponse, error)
	CreateChapter(ctx context.Context, in *CreateChapterRequest, opts ...grpc.CallOption) (*Chapter, error)
	UpdateChapter(ctx context.Context, in *UpdateChapterRequest, opts ...grpc.CallOption) (*Chapter, error)
	DeleteChapter(ctx context.Context, in *DeleteChapterRequest, opts ...grpc.CallOption) (*DeleteChapterResponse, error)
	ListGenres(ctx context.Context, in *ListGenresRequest, opts ...grpc.CallOption) (*ListGenresResponse, error)
	CreateGenre(ctx context.Context, in *CreateGenreRequest, opts ...grpc.CallOption) (*Genre, error)
	DeleteGenre(ctx context.Context, in *DeleteGenreRequest, opts ...grpc.CallOption) (*DeleteGenreResponse, error)
}

type novelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNovelServiceClient(cc grpc.ClientConnInterface) NovelServiceClient {
	return &novelServiceClient{cc}
}

func (c *novelServiceClient) GetNovel(ctx context.Context, in *GetNovelRequest, opts ...grpc.CallOption) (*Novel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Novel)
	err := c.cc.Invoke(ctx, NovelService_GetNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListNovels(ctx context.Context, in *ListNovelsRequest, opts ...grpc.CallOption) (*ListNovelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNovelsResponse)
	err := c.cc.Invoke(ctx, NovelService_ListNovels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) CreateNovel(ctx context.Context, in *CreateNovelRequest, opts ...grpc.CallOption) (*Novel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Novel)
	err := c.cc.Invoke(ctx, NovelService_CreateNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) UpdateNovel(ctx context.Context, in *UpdateNovelRequest, opts ...grpc.CallOption) (*Novel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Novel)
	err := c.cc.Invoke(ctx, NovelService_UpdateNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) DeleteNovel(ctx context.Context, in *DeleteNovelRequest, opts ...grpc.CallOption) (*DeleteNovelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNovelResponse)
	err := c.cc.Invoke(ctx, NovelService_DeleteNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) GetChapter(ctx context.Context, in *GetChapterRequest, opts ...grpc.CallOption) (*Chapter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Chapter)
	err := c.cc.Invoke(ctx, NovelService_GetChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListChapters(ctx context.Context, in *ListChaptersRequest, opts ...grpc.CallOption) (*ListChaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChaptersResponse)
	err := c.cc.Invoke(ctx, NovelService_ListChapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) CreateChapter(ctx context.Context, in *CreateChapterRequest, opts ...grpc.CallOption) (*Chapter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Chapter)
	err := c.cc.Invoke(ctx, NovelService_CreateChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) UpdateChapter(ctx context.Context, in *UpdateChapterRequest, opts ...grpc.CallOption) (*Chapter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Chapter)
	err := c.cc.Invoke(ctx, NovelService_UpdateChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) DeleteChapter(ctx context.Context, in *DeleteChapterRequest, opts ...grpc.CallOption) (*DeleteChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChapterResponse)
	err := c.cc.Invoke(ctx, NovelService_DeleteChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListGenres(ctx context.Context, in *ListGenresRequest, opts ...grpc.CallOption) (*ListGenresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGenresResponse)
	err := c.cc.Invoke(ctx, NovelService_ListGenres_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) CreateGenre(ctx context.Context, in *CreateGenreRequest, opts ...grpc.CallOption) (*Genre, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Genre)
	err := c.cc.Invoke(ctx, NovelService_CreateGenre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) DeleteGenre(ctx context.Context, in *DeleteGenreRequest, opts ...grpc.CallOption) (*DeleteGenreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGenreResponse)
	err := c.cc.Invoke(ctx, NovelService_DeleteGenre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NovelServiceServer is the server API for NovelService service.
// All implementations must embed UnimplementedNovelServiceServer
// for forward compatibility.
type NovelServiceServer interface {
	GetNovel(context.Context, *GetNovelRequest) (*Novel, error)
	ListNovels(context.Context, *ListNovelsRequest) (*ListNovelsResponse, error)
	CreateNovel(context.Context, *CreateNovelRequest) (*Novel, error)
	UpdateNovel(context.Context, *UpdateNovelRequest) (*Novel, error)
	DeleteNovel(context.Context, *DeleteNovelRequest) (*DeleteNovelResponse, error)
	GetChapter(context.Context, *GetChapterRequest) (*Chapter, error)
	ListChapters(context.Context, *ListChaptersRequest) (*ListChaptersResponse, error)
	CreateChapter(context.Context, *CreateChapterRequest) (*Chapter, error)
	UpdateChapter(context.Context, *UpdateChapterRequest) (*Chapter, error)
	DeleteChapter(context.Context, *DeleteChapterRequest) (*DeleteChapterResponse, error)
	ListGenres(context.Context, *ListGenresRequest) (*ListGenresResponse, error)
	CreateGenre(context.Context, *CreateGenreRequest) (*Genre, error)
	DeleteGenre(context.Context, *DeleteGenreRequest) (*DeleteGenreResponse, error)
	mustEmbedUnimplementedNovelServiceServer()
}

// UnimplementedNovelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNovelServiceServer struct{}

func (UnimplementedNovelServiceServer) GetNovel(context.Context, *GetNovelRequest) (*Novel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNovel not implemented")
}
func (UnimplementedNovelServiceServer) ListNovels(context.Context, *ListNovelsRequest) (*ListNovelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNovels not implemented")
}
func (UnimplementedNovelServiceServer) CreateNovel(context.Context, *CreateNovelRequest) (*Novel, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNovel not implemented")
}
func (UnimplementedNovelServiceServer) UpdateNovel(context.Context, *UpdateNovelRequest) (*Novel, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNovel not implemented")
}
func (UnimplementedNovelServiceServer) DeleteNovel(context.Context, *DeleteNovelRequest) (*DeleteNovelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNovel not implemented")
}
func (UnimplementedNovelServiceServer) GetChapter(context.Context, *GetChapterRequest) (*Chapter, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChapter not implemented")
}
func (UnimplementedNovelServiceServer) ListChapters(context.Context, *ListChaptersRequest) (*ListChaptersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChapters not implemented")
}
func (UnimplementedNovelServiceServer) CreateChapter(context.Context, *CreateChapterRequest) (*Chapter, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChapter not implemented")
}
func (UnimplementedNovelServiceServer) UpdateChapter(context.Context, *UpdateChapterRequest) (*Chapter, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChapter not implemented")
}
func (UnimplementedNovelServiceServer) DeleteChapter(context.Context, *DeleteChapterRequest) (*DeleteChapterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChapter not implemented")
}
func (UnimplementedNovelServiceServer) ListGenres(context.Context, *ListGenresRequest) (*ListGenresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGenres not implemented")
}
func (UnimplementedNovelServiceServer) CreateGenre(context.Context, *CreateGenreRequest) (*Genre, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGenre not implemented")
}
func (UnimplementedNovelServiceServer) DeleteGenre(context.Context, *DeleteGenreRequest) (*DeleteGenreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGenre not implemented")
}
func (UnimplementedNovelServiceServer) mustEmbedUnimplementedNovelServiceServer() {}
func (UnimplementedNovelServiceServer) testEmbeddedByValue()                      {}

// UnsafeNovelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NovelServiceServer will
// result in compilation errors.
type UnsafeNovelServiceServer interface {
	mustEmbedUnimplementedNovelServiceServer()
}

func RegisterNovelServiceServer(s grpc.ServiceRegistrar, srv NovelServiceServer) {
	// If the following call panics, it indicates UnimplementedNovelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NovelService_ServiceDesc, srv)
}

func _NovelService_GetNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNovelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).GetNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_GetNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).GetNovel(ctx, req.(*GetNovelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListNovels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNovelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListNovels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListNovels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListNovels(ctx, req.(*ListNovelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_CreateNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNovelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).CreateNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_CreateNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).CreateNovel(ctx, req.(*CreateNovelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_UpdateNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNovelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).UpdateNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_UpdateNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).UpdateNovel(ctx, req.(*UpdateNovelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_DeleteNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNovelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).DeleteNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_DeleteNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).DeleteNovel(ctx, req.(*DeleteNovelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_GetChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).GetChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_GetChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).GetChapter(ctx, req.(*GetChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListChapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListChapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListChapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListChapters(ctx, req.(*ListChaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_CreateChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).CreateChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_CreateChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).CreateChapter(ctx, req.(*CreateChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_UpdateChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).UpdateChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_UpdateChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).UpdateChapter(ctx, req.(*UpdateChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_DeleteChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).DeleteChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_DeleteChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).DeleteChapter(ctx, req.(*DeleteChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListGenres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGenresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListGenres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListGenres_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListGenres(ctx, req.(*ListGenresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_CreateGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGenreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).CreateGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_CreateGenre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).CreateGenre(ctx, req.(*CreateGenreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_DeleteGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGenreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).DeleteGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_DeleteGenre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).DeleteGenre(ctx, req.(*DeleteGenreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NovelService_ServiceDesc is the grpc.ServiceDesc for NovelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NovelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novel.v1.NovelService",
	HandlerType: (*NovelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNovel",
			Handler:    _NovelService_GetNovel_Handler,
		},
		{
			MethodName: "ListNovels",
			Handler:    _NovelService_ListNovels_Handler,
		},
		{
			MethodName: "CreateNovel",
			Handler:    _NovelService_CreateNovel_Handler,
		},
		{
			MethodName: "UpdateNovel",
			Handler:    _NovelService_UpdateNovel_Handler,
		},
		{
			MethodName: "DeleteNovel",
			Handler:    _NovelService_DeleteNovel_Handler,
		},
		{
			MethodName: "GetChapter",
			Handler:    _NovelService_GetChapter_Handler,
		},
		{
			MethodName: "ListChapters",
			Handler:    _NovelService_ListChapters_Handler,
		},
		{
			MethodName: "CreateChapter",
			Handler:    _NovelService_CreateChapter_Handler,
		},
		{
			MethodName: "UpdateChapter",
			Handler:    _NovelService_UpdateChapter_Handler,
		},
		{
			MethodName: "DeleteChapter",
			Handler:    _NovelService_DeleteChapter_Handler,
		},
		{
			MethodName: "ListGenres",
			Handler:    _NovelService_ListGenres_Handler,
		},
		{
			MethodName: "CreateGenre",
			Handler:    _NovelService_CreateGenre_Handler,
		},
		{
			MethodName: "DeleteGenre",
			Handler:    _NovelService_DeleteGenre_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novel.proto",
}
