// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/novel/v1/novel.proto

package novelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Novel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Synopsis      string                 `protobuf:"bytes,4,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,8,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Genres        []*Genre               `protobuf:"bytes,9,rep,name=genres,proto3" json:"genres,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Novel) Reset() {
	*x = Novel{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Novel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Novel) ProtoMessage() {}

func (x *Novel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Novel.ProtoReflect.Descriptor instead.
func (*Novel) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{0}
}

func (x *Novel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Novel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Novel) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Novel) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *Novel) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Novel) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Novel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Novel) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Novel) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Novel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Novel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{1}
}

func (x *Genre) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genre) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NovelId       string                 `protobuf:"bytes,2,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	Number        int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	WordCount     int32                  `protobuf:"varint,6,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{2}
}

func (x *Chapter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chapter) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *Chapter) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chapter) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *Chapter) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetNovelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNovelRequest) Reset() {
	*x = GetNovelRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNovelRequest) ProtoMessage() {}

func (x *GetNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNovelRequest.ProtoReflect.Descriptor instead.
func (*GetNovelRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{3}
}

func (x *GetNovelRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ListNovelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	GenreSlug     string                 `protobuf:"bytes,3,opt,name=genre_slug,json=genreSlug,proto3" json:"genre_slug,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNovelsRequest) Reset() {
	*x = ListNovelsRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNovelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelsRequest) ProtoMessage() {}

func (x *ListNovelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelsRequest.ProtoReflect.Descriptor instead.
func (*ListNovelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{4}
}

func (x *ListNovelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNovelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNovelsRequest) GetGenreSlug() string {
	if x != nil {
		return x.GenreSlug
	}
	return ""
}

func (x *ListNovelsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListNovelsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ListNovelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Novels        []*Novel               `protobuf:"bytes,1,rep,name=novels,proto3" json:"novels,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNovelsResponse) Reset() {
	*x = ListNovelsResponse{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNovelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelsResponse) ProtoMessage() {}

func (x *ListNovelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelsResponse.ProtoReflect.Descriptor instead.
func (*ListNovelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{5}
}

func (x *ListNovelsResponse) GetNovels() []*Novel {
	if x != nil {
		return x.Novels
	}
	return nil
}

func (x *ListNovelsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNovelsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNovelsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateNovelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Synopsis      string                 `protobuf:"bytes,2,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	GenreIds      []int32                `protobuf:"varint,5,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNovelRequest) Reset() {
	*x = CreateNovelRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNovelRequest) ProtoMessage() {}

func (x *CreateNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNovelRequest.ProtoReflect.Descriptor instead.
func (*CreateNovelRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNovelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNovelRequest) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *CreateNovelRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreateNovelRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateNovelRequest) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

type UpdateNovelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Synopsis      string                 `protobuf:"bytes,3,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	GenreIds      []int32                `protobuf:"varint,7,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNovelRequest) Reset() {
	*x = UpdateNovelRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNovelRequest) ProtoMessage() {}

func (x *UpdateNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNovelRequest.ProtoReflect.Descriptor instead.
func (*UpdateNovelRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNovelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNovelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNovelRequest) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *UpdateNovelRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *UpdateNovelRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UpdateNovelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateNovelRequest) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

type DeleteNovelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNovelRequest) Reset() {
	*x = DeleteNovelRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNovelRequest) ProtoMessage() {}

func (x *DeleteNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNovelRequest.ProtoReflect.Descriptor instead.
func (*DeleteNovelRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNovelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteNovelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNovelResponse) Reset() {
	*x = DeleteNovelResponse{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNovelResponse) ProtoMessage() {}

func (x *DeleteNovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNovelResponse.ProtoReflect.Descriptor instead.
func (*DeleteNovelResponse) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNovelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelSlug     string                 `protobuf:"bytes,1,opt,name=novel_slug,json=novelSlug,proto3" json:"novel_slug,omitempty"`
	ChapterNumber int32                  `protobuf:"varint,2,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterRequest) Reset() {
	*x = GetChapterRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterRequest) ProtoMessage() {}

func (x *GetChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterRequest.ProtoReflect.Descriptor instead.
func (*GetChapterRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{10}
}

func (x *GetChapterRequest) GetNovelSlug() string {
	if x != nil {
		return x.NovelSlug
	}
	return ""
}

func (x *GetChapterRequest) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

type ListChaptersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelId       string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChaptersRequest) Reset() {
	*x = ListChaptersRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChaptersRequest) ProtoMessage() {}

func (x *ListChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChaptersRequest.ProtoReflect.Descriptor instead.
func (*ListChaptersRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{11}
}

func (x *ListChaptersRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *ListChaptersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChaptersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*ChapterSummary      `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChaptersResponse) Reset() {
	*x = ListChaptersResponse{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChaptersResponse) ProtoMessage() {}

func (x *ListChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChaptersResponse.ProtoReflect.Descriptor instead.
func (*ListChaptersResponse) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{12}
}

func (x *ListChaptersResponse) GetChapters() []*ChapterSummary {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *ListChaptersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ChapterSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	WordCount     int32                  `protobuf:"varint,4,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterSummary) Reset() {
	*x = ChapterSummary{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterSummary) ProtoMessage() {}

func (x *ChapterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterSummary.ProtoReflect.Descriptor instead.
func (*ChapterSummary) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{13}
}

func (x *ChapterSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChapterSummary) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ChapterSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterSummary) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ChapterSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelId       string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterRequest) Reset() {
	*x = CreateChapterRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterRequest) ProtoMessage() {}

func (x *CreateChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterRequest.ProtoReflect.Descriptor instead.
func (*CreateChapterRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{14}
}

func (x *CreateChapterRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *CreateChapterRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CreateChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChapterRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChapterRequest) Reset() {
	*x = UpdateChapterRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChapterRequest) ProtoMessage() {}

func (x *UpdateChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChapterRequest.ProtoReflect.Descriptor instead.
func (*UpdateChapterRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateChapterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateChapterRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListGenresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGenresRequest) Reset() {
	*x = ListGenresRequest{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenresRequest) ProtoMessage() {}

func (x *ListGenresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGenresRequest.ProtoReflect.Descriptor instead.
func (*ListGenresRequest) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{16}
}

type ListGenresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*Genre               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGenresResponse) Reset() {
	*x = ListGenresResponse{}
	mi := &file_proto_novel_v1_novel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenresResponse) ProtoMessage() {}

func (x *ListGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_novel_v1_novel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGenresResponse.ProtoReflect.Descriptor instead.
func (*ListGenresResponse) Descriptor() ([]byte, []int) {
	return file_proto_novel_v1_novel_proto_rawDescGZIP(), []int{17}
}

func (x *ListGenresResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

var File_proto_novel_v1_novel_proto protoreflect.FileDescriptor

const file_proto_novel_v1_novel_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/novel/v1/novel.proto\x12\bnovel.v1\"\xb8\x02\n" +
	"\x05Novel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1a\n" +
	"\bsynopsis\x18\x04 \x01(\tR\bsynopsis\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\b \x01(\x05R\rtotalChapters\x12'\n" +
	"\x06genres\x18\t \x03(\v2\x0f.novel.v1.GenreR\x06genres\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"?\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"\xba\x01\n" +
	"\aChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnovel_id\x18\x02 \x01(\tR\anovelId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"word_count\x18\x06 \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"%\n" +
	"\x0fGetNovelRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x94\x01\n" +
	"\x11ListNovelsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"genre_slug\x18\x03 \x01(\tR\tgenreSlug\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\"\x84\x01\n" +
	"\x12ListNovelsResponse\x12'\n" +
	"\x06novels\x18\x01 \x03(\v2\x0f.novel.v1.NovelR\x06novels\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x98\x01\n" +
	"\x12CreateNovelRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bsynopsis\x18\x02 \x01(\tR\bsynopsis\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1b\n" +
	"\tgenre_ids\x18\x05 \x03(\x05R\bgenreIds\"\xc0\x01\n" +
	"\x12UpdateNovelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsynopsis\x18\x03 \x01(\tR\bsynopsis\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tgenre_ids\x18\a \x03(\x05R\bgenreIds\"$\n" +
	"\x12DeleteNovelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteNovelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x11GetChapterRequest\x12\x1d\n" +
	"\n" +
	"novel_slug\x18\x01 \x01(\tR\tnovelSlug\x12%\n" +
	"\x0echapter_number\x18\x02 \x01(\x05R\rchapterNumber\"a\n" +
	"\x13ListChaptersRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"b\n" +
	"\x14ListChaptersResponse\x124\n" +
	"\bchapters\x18\x01 \x03(\v2\x18.novel.v1.ChapterSummaryR\bchapters\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8c\x01\n" +
	"\x0eChapterSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"word_count\x18\x04 \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"y\n" +
	"\x14CreateChapterRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"V\n" +
	"\x14UpdateChapterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x13\n" +
	"\x11ListGenresRequest\"=\n" +
	"\x12ListGenresResponse\x12'\n" +
	"\x06genres\x18\x01 \x03(\v2\x0f.novel.v1.GenreR\x06genres2\xb5\x05\n" +
	"\fNovelService\x126\n" +
	"\bGetNovel\x12\x19.novel.v1.GetNovelRequest\x1a\x0f.novel.v1.Novel\x12G\n" +
	"\n" +
	"ListNovels\x12\x1b.novel.v1.ListNovelsRequest\x1a\x1c.novel.v1.ListNovelsResponse\x12<\n" +
	"\vCreateNovel\x12\x1c.novel.v1.CreateNovelRequest\x1a\x0f.novel.v1.Novel\x12<\n" +
	"\vUpdateNovel\x12\x1c.novel.v1.UpdateNovelRequest\x1a\x0f.novel.v1.Novel\x12J\n" +
	"\vDeleteNovel\x12\x1c.novel.v1.DeleteNovelRequest\x1a\x1d.novel.v1.DeleteNovelResponse\x12<\n" +
	"\n" +
	"GetChapter\x12\x1b.novel.v1.GetChapterRequest\x1a\x11.novel.v1.Chapter\x12M\n" +
	"\fListChapters\x12\x1d.novel.v1.ListChaptersRequest\x1a\x1e.novel.v1.ListChaptersResponse\x12B\n" +
	"\rCreateChapter\x12\x1e.novel.v1.CreateChapterRequest\x1a\x11.novel.v1.Chapter\x12B\n" +
	"\rUpdateChapter\x12\x1e.novel.v1.UpdateChapterRequest\x1a\x11.novel.v1.Chapter\x12G\n" +
	"\n" +
	"ListGenres\x12\x1b.novel.v1.ListGenresRequest\x1a\x1c.novel.v1.ListGenresResponseB-Z+github.com/novelhive/proto/novel/v1;novelv1b\x06proto3"

var (
	file_proto_novel_v1_novel_proto_rawDescOnce sync.Once
	file_proto_novel_v1_novel_proto_rawDescData []byte
)

func file_proto_novel_v1_novel_proto_rawDescGZIP() []byte {
	file_proto_novel_v1_novel_proto_rawDescOnce.Do(func() {
		file_proto_novel_v1_novel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_novel_v1_novel_proto_rawDesc), len(file_proto_novel_v1_novel_proto_rawDesc)))
	})
	return file_proto_novel_v1_novel_proto_rawDescData
}

var file_proto_novel_v1_novel_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_novel_v1_novel_proto_goTypes = []any{
	(*Novel)(nil),                // 0: novel.v1.Novel
	(*Genre)(nil),                // 1: novel.v1.Genre
	(*Chapter)(nil),              // 2: novel.v1.Chapter
	(*GetNovelRequest)(nil),      // 3: novel.v1.GetNovelRequest
	(*ListNovelsRequest)(nil),    // 4: novel.v1.ListNovelsRequest
	(*ListNovelsResponse)(nil),   // 5: novel.v1.ListNovelsResponse
	(*CreateNovelRequest)(nil),   // 6: novel.v1.CreateNovelRequest
	(*UpdateNovelRequest)(nil),   // 7: novel.v1.UpdateNovelRequest
	(*DeleteNovelRequest)(nil),   // 8: novel.v1.DeleteNovelRequest
	(*DeleteNovelResponse)(nil),  // 9: novel.v1.DeleteNovelResponse
	(*GetChapterRequest)(nil),    // 10: novel.v1.GetChapterRequest
	(*ListChaptersRequest)(nil),  // 11: novel.v1.ListChaptersRequest
	(*ListChaptersResponse)(nil), // 12: novel.v1.ListChaptersResponse
	(*ChapterSummary)(nil),       // 13: novel.v1.ChapterSummary
	(*CreateChapterRequest)(nil), // 14: novel.v1.CreateChapterRequest
	(*UpdateChapterRequest)(nil), // 15: novel.v1.UpdateChapterRequest
	(*ListGenresRequest)(nil),    // 16: novel.v1.ListGenresRequest
	(*ListGenresResponse)(nil),   // 17: novel.v1.ListGenresResponse
}
var file_proto_novel_v1_novel_proto_depIdxs = []int32{
	1,  // 0: novel.v1.Novel.genres:type_name -> novel.v1.Genre
	0,  // 1: novel.v1.ListNovelsResponse.novels:type_name -> novel.v1.Novel
	13, // 2: novel.v1.ListChaptersResponse.chapters:type_name -> novel.v1.ChapterSummary
	1,  // 3: novel.v1.ListGenresResponse.genres:type_name -> novel.v1.Genre
	3,  // 4: novel.v1.NovelService.GetNovel:input_type -> novel.v1.GetNovelRequest
	4,  // 5: novel.v1.NovelService.ListNovels:input_type -> novel.v1.ListNovelsRequest
	6,  // 6: novel.v1.NovelService.CreateNovel:input_type -> novel.v1.CreateNovelRequest
	7,  // 7: novel.v1.NovelService.UpdateNovel:input_type -> novel.v1.UpdateNovelRequest
	8,  // 8: novel.v1.NovelService.DeleteNovel:input_type -> novel.v1.DeleteNovelRequest
	10, // 9: novel.v1.NovelService.GetChapter:input_type -> novel.v1.GetChapterRequest
	11, // 10: novel.v1.NovelService.ListChapters:input_type -> novel.v1.ListChaptersRequest
	14, // 11: novel.v1.NovelService.CreateChapter:input_type -> novel.v1.CreateChapterRequest
	15, // 12: novel.v1.NovelService.UpdateChapter:input_type -> novel.v1.UpdateChapterRequest
	16, // 13: novel.v1.NovelService.ListGenres:input_type -> novel.v1.ListGenresRequest
	0,  // 14: novel.v1.NovelService.GetNovel:output_type -> novel.v1.Novel
	5,  // 15: novel.v1.NovelService.ListNovels:output_type -> novel.v1.ListNovelsResponse
	0,  // 16: novel.v1.NovelService.CreateNovel:output_type -> novel.v1.Novel
	0,  // 17: novel.v1.NovelService.UpdateNovel:output_type -> novel.v1.Novel
	9,  // 18: novel.v1.NovelService.DeleteNovel:output_type -> novel.v1.DeleteNovelResponse
	2,  // 19: novel.v1.NovelService.GetChapter:output_type -> novel.v1.Chapter
	12, // 20: novel.v1.NovelService.ListChapters:output_type -> novel.v1.ListChaptersResponse
	2,  // 21: novel.v1.NovelService.CreateChapter:output_type -> novel.v1.Chapter
	2,  // 22: novel.v1.NovelService.UpdateChapter:output_type -> novel.v1.Chapter
	17, // 23: novel.v1.NovelService.ListGenres:output_type -> novel.v1.ListGenresResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_novel_v1_novel_proto_init() }
func file_proto_novel_v1_novel_proto_init() {
	if File_proto_novel_v1_novel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_novel_v1_novel_proto_rawDesc), len(file_proto_novel_v1_novel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_novel_v1_novel_proto_goTypes,
		DependencyIndexes: file_proto_novel_v1_novel_proto_depIdxs,
		MessageInfos:      file_proto_novel_v1_novel_proto_msgTypes,
	}.Build()
	File_proto_novel_v1_novel_proto = out.File
	file_proto_novel_v1_novel_proto_goTypes = nil
	file_proto_novel_v1_novel_proto_depIdxs = nil
}
